title: CSC2621 Topics in Robotics - Reinforcement Learning (Winter 2020)
description: CSC2621-W20 course website
sitename: CSC2621-W20
baseurl: '/csc2621-w20/'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - contents
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
markdown: kramdown

theme: jekyll-theme-cayman